from enum import Enum
from models import *
from .analysis_type import AnalysisType
from .feature_type import FeatureType
from .band_frequence import BandFrequence

class AiType(Enum):
    DEATH_PROGNOSTIC_CLINICAL_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas clinicas)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.CLINICAL))
    DEATH_PROGNOSTIC_STATISTIC_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas estatisticas)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.STATISTIC))
    DEATH_PROGNOSTIC_STATISTIC_AND_CLINICAL_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas estatisticas e clinicas)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.STATISTIC_AND_CLINICAL))
    DEATH_PROGNOSTIC_PCP_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas de PCP)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.PCP))
    DEATH_PROGNOSTIC_PCP_AND_CLINICAL_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas de PCP e clinicas)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.PCP_AND_CLINICAL))
    DEATH_PROGNOSTIC_COHERENCE_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas de Coerência)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.COHERENCE))
    DEATH_PROGNOSTIC_COHERENCE_AND_CLINICAL_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas de Coerência e clinicas)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.COHERENCE_AND_CLINICAL))
    DEATH_PROGNOSTIC_FM_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas de FM)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.FM))
    DEATH_PROGNOSTIC_FM_AND_CLINICAL_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas de FM e clinicas)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.FM_AND_CLINICAL))
    DEATH_PROGNOSTIC_SIGNAL = ('Cenario para prognostico de Morte (CNN LSTM Somente Pelo sinal Puro)', CnnLstm(AnalysisType.DEATH_PROGNOSTIC, FeatureType.CLINICAL))
    DEATH_PROGNOSTIC_MLP_CLINICAL = ('Cenario para prognostico de Morte (MLP Caracteristicas Clinicas)', Mlp(AnalysisType.DEATH_PROGNOSTIC, FeatureType.CLINICAL, None))
    DEATH_PROGNOSTIC_CLINICAL_FRONTAL_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas clinicas Canais Frontais)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.CLINICAL_FRONTAL))
    DEATH_PROGNOSTIC_CLINICAL_PARIENTAL_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas clinicas Canais Parientais)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.CLINICAL_PARIENTAL))
    DEATH_PROGNOSTIC_CLINICAL_CENTRAL_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas clinicas Canais Centrais)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.CLINICAL_CENTRAL))
    DEATH_PROGNOSTIC_CLINICAL_OCCIPITAL_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas clinicas Canais Occipitais)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.CLINICAL_OCCIPITAL))
    DEATH_PROGNOSTIC_CLINICAL_TEMPORAL_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas clinicas Canais Temporais)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.CLINICAL_TEMPORAL))
    DEATH_PROGNOSTIC_COMMON_SPATIAL_PATTERN_4 = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas Common Spatial Pattern 4 Valores)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.COMMON_SPATIAL_PATTERNS_4))
    DEATH_PROGNOSTIC_COMMON_SPATIAL_PATTERN_10 = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas Common Spatial Pattern 10 Valores)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.COMMON_SPATIAL_PATTERNS_10))
    DEATH_PROGNOSTIC_COMMON_SPATIAL_PATTERN_20 = ('Cenario para prognostico de Morte (CNN + LSTM + caracteristicas Common Spatial Pattern 20 Valores)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.COMMON_SPATIAL_PATTERNS_20))
    DEATH_PROGNOSTIC_TRANFORMER_CLINICAL_FEATURE = ('Cenario para prognostico de Morte (CNN + Transformer + caracteristicas clinicas)', CnnTranformerEncodeFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.CLINICAL))    
    DEATH_PROGNOSTIC_TRANFORMER_STATISTIC_FEATURE = ('Cenario para prognostico de Morte (CNN + Transformer + caracteristicas estatisticas)', CnnTranformerEncodeFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.STATISTIC))    
    DEATH_PROGNOSTIC_TRANFORMER_PCP_FEATURE = ('Cenario para prognostico de Morte (CNN + Transformer + caracteristicas de PCP)', CnnTranformerEncodeFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.PCP))    
    DEATH_PROGNOSTIC_TRANFORMER_FM_FEATURE = ('Cenario para prognostico de Morte (CNN + Transformer + caracteristicas de FM)', CnnTranformerEncodeFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.FM))    
    DEATH_PROGNOSTIC_TRANFORMER_COHERENCE_FEATURE = ('Cenario para prognostico de Morte (CNN + Transformer + caracteristicas de Coerência)', CnnTranformerEncodeFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.COHERENCE))    
    DEATH_PROGNOSTIC_STATISTIC_TUNNING_FEATURE = ('Cenario para prognostico de Morte (CNN + Tunning + caracteristicas estatisticas)', CnnTunningFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.STATISTIC))    
    DEATH_PROGNOSTIC_WAVELET_DECOMPOSITION_FEATURE = ('Cenario para prognostico de Morte (CNN + LSTM + Caracteristicas de Decomposição Wavelet)', CnnLstmFeatures(AnalysisType.DEATH_PROGNOSTIC, FeatureType.WAVELET_DECOMPOSITION))
    ETIOLOGY_CLINICAL_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas clinicas)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.CLINICAL))
    ETIOLOGY_STATISTIC_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas estatisticas)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.STATISTIC))
    ETIOLOGY_STATISTIC_AND_CLINICAL_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas estatisticas e clinicas)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.STATISTIC_AND_CLINICAL))
    ETIOLOGY_PCP_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas de PCP)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.PCP))
    ETIOLOGY_PCP_AND_CLINICAL_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas de PCP e clinicas)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.PCP_AND_CLINICAL))
    ETIOLOGY_COHERENCE_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas de Coerencia)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.COHERENCE))
    ETIOLOGY_COHERENCE_AND_CLINICAL_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas de Coerência e Clinicas)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.COHERENCE_AND_CLINICAL))
    ETIOLOGY_FM_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas de FM)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.FM))
    ETIOLOGY_FM_AND_CLINICAL_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas de FM e clinicas)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.FM_AND_CLINICAL))
    ETIOLOGY_SIGNAL = ('Cenario para classificação da etiologia (CNN LSTM Somente Pelo sinal Puro)', CnnLstm(AnalysisType.ETIOLOGY, FeatureType.CLINICAL))
    ETIOLOGY_MLP_CLINICAL = ('Cenario para classificação da etiologia (MLP Caracteristicas Clinicas)', Mlp(AnalysisType.ETIOLOGY, FeatureType.CLINICAL, None))
    ETIOLOGY_WAVELET_DECOMPOSITION_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + Caracteristicas de Decomposição Wavelet)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.WAVELET_DECOMPOSITION))
    ETIOLOGY_CLINICAL_FRONTAL_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas clinicas Canais Frontais)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.CLINICAL_FRONTAL))
    ETIOLOGY_CLINICAL_PARIENTAL_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas clinicas Canais Parientais)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.CLINICAL_PARIENTAL))
    ETIOLOGY_CLINICAL_CENTRAL_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas clinicas Canais Centrais)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.CLINICAL_CENTRAL))
    ETIOLOGY_CLINICAL_OCCIPITAL_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas clinicas Canais Occipitais)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.CLINICAL_OCCIPITAL))
    ETIOLOGY_CLINICAL_TEMPORAL_FEATURE = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas clinicas Canais Temporais)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.CLINICAL_TEMPORAL))
    ETIOLOGY_COMMON_SPATIAL_PATTERN_4 = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas Common Spatial Pattern 4 Valores)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.COMMON_SPATIAL_PATTERNS_4))
    ETIOLOGY_COMMON_SPATIAL_PATTERN_10 = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas Common Spatial Pattern 10 Valores)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.COMMON_SPATIAL_PATTERNS_10))
    ETIOLOGY_COMMON_SPATIAL_PATTERN_20 = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas Common Spatial Pattern 20 Valores)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.COMMON_SPATIAL_PATTERNS_20))
    ETIOLOGY_COMMON_SPATIAL_PATTERN_100 = ('Cenario para classificação da etiologia (CNN + LSTM + caracteristicas Common Spatial Pattern 100 Valores)', CnnLstmFeatures(AnalysisType.ETIOLOGY, FeatureType.COMMON_SPATIAL_PATTERNS_100))
    ETIOLOGY_STATISTIC_TUNNING_FEATURE = ('Cenario para classificação da etiologia (CNN + Tunning + caracteristicas estatisticas)', CnnTunningFeatures(AnalysisType.ETIOLOGY, FeatureType.STATISTIC))
    ETIOLOGY_STATISTIC_TUNNING_FRONTAIS_FEATURE = ('Cenario para classificação da etiologia (CNN + Tunning + caracteristicas clinicas Canais Frontais)', CnnTunningFeatures(AnalysisType.ETIOLOGY, FeatureType.CLINICAL_FRONTAL))
    MUSIC_LIKE_CLINICAL_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas clinicas)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.CLINICAL))
    MUSIC_LIKE_STATISTIC_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas estatisticas)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.STATISTIC))
    MUSIC_LIKE_STATISTIC_AND_CLINICAL_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas estatisticas e clinicas)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.STATISTIC_AND_CLINICAL))
    MUSIC_LIKE_PCP_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas de PCP)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.PCP))
    MUSIC_LIKE_PCP_AND_CLINICAL_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas de PCP e clinicas)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.PCP_AND_CLINICAL))
    MUSIC_LIKE_FM_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas de FM)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.FM))
    MUSIC_LIKE_FM_AND_CLINICAL_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas de FM e clinicas)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.FM_AND_CLINICAL))
    MUSIC_LIKE_COHERENCE_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas de Coerência)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.COHERENCE))
    MUSIC_LIKE_COHERENCE_AND_CLINICAL_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas de Coerência e clinicas)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.COHERENCE_AND_CLINICAL))
    MUSIC_LIKE_SIGNAL = ('Cenario para Gosto Musical (CNN LSTM Somente Pelo sinal Puro)', CnnLstm(AnalysisType.MUSIC_LIKE, FeatureType.CLINICAL))
    MUSIC_LIKE_MLP_CLINICAL = ('Cenario para Gosto Musical (MLP Caracteristicas Clinicas)', Mlp(AnalysisType.MUSIC_LIKE, FeatureType.CLINICAL, None))
    MUSIC_LIKE_MLP_PCP = ('Cenario para Gosto Musical (MLP Caracteristicas PCP)', Mlp(AnalysisType.MUSIC_LIKE, FeatureType.PCP, None))
    MUSIC_LIKE_MLP_PCP_ALFA = ('Cenario para Gosto Musical (MLP Caracteristicas PCP Banda Alfa)', Mlp(AnalysisType.MUSIC_LIKE, FeatureType.PCP, [BandFrequence.ALFA]))
    MUSIC_LIKE_MLP_PCP_BETA = ('Cenario para Gosto Musical (MLP Caracteristicas PCP Banda Beta)', Mlp(AnalysisType.MUSIC_LIKE, FeatureType.PCP, [BandFrequence.BETA]))
    MUSIC_LIKE_MLP_PCP_GAMA = ('Cenario para Gosto Musical (MLP Caracteristicas PCP Banda Gama)', Mlp(AnalysisType.MUSIC_LIKE, FeatureType.PCP, [BandFrequence.GAMA]))
    MUSIC_LIKE_MLP_PCP_SUPER_GAMA = ('Cenario para Gosto Musical (MLP Caracteristicas PCP Banda Super Gama)', Mlp(AnalysisType.MUSIC_LIKE, FeatureType.PCP, [BandFrequence.SUPERGAMA]))
    MUSIC_LIKE_MLP_PCP_DELTA = ('Cenario para Gosto Musical (MLP Caracteristicas PCP Banda Delta)', Mlp(AnalysisType.MUSIC_LIKE, FeatureType.PCP, [BandFrequence.DELTA]))
    MUSIC_LIKE_MLP_PCP_TETA = ('Cenario para Gosto Musical (MLP Caracteristicas PCP Banda Teta)', Mlp(AnalysisType.MUSIC_LIKE, FeatureType.PCP, [BandFrequence.TETA]))
    MUSIC_LIKE_MLP_PCP_DELTA_TETA_SUPER_GAMA = ('Cenario para Gosto Musical (MLP Caracteristicas PCP Banda Delta, Teta, Super Gama)', Mlp(AnalysisType.MUSIC_LIKE, FeatureType.PCP, [BandFrequence.DELTA, BandFrequence.TETA, BandFrequence.SUPERGAMA]))
    MUSIC_LIKE_MLP_STATISTIC = ('Cenario para Gosto Musical (MLP Caracteristicas estatisticas)', Mlp(AnalysisType.MUSIC_LIKE, FeatureType.STATISTIC, None))
    MUSIC_LIKE_WAVELET_DECOMPOSITION_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas de Decomposição Wavelet)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.WAVELET_DECOMPOSITION))
    MUSIC_LIKE_CLINICAL_FRONTAL_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas clinicas Canais Frontais)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.CLINICAL_FRONTAL))
    MUSIC_LIKE_CLINICAL_PARIENTAL_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas clinicas Canais Parientais)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.CLINICAL_PARIENTAL))
    MUSIC_LIKE_CLINICAL_CENTRAL_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas clinicas Canais Centrais)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.CLINICAL_CENTRAL))
    MUSIC_LIKE_CLINICAL_OCCIPITAL_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas clinicas Canais Occipitais)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.CLINICAL_OCCIPITAL))
    MUSIC_LIKE_CLINICAL_TEMPORAL_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas clinicas Canais Temporais)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.CLINICAL_TEMPORAL))
    MUSIC_LIKE_CLINICAL_T3_T4_Pz_O2_Oz_FEATURE = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas clinicas Canais T3 T4 Pz O2 Oz)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.CLINICAL_T3_T4_Pz_O2_Oz))
    MUSIC_LIKE_SIGNAL_T3_T4_Pz_O2_Oz = ('Cenario para Gosto Musical (CNN LSTM Somente Pelo sinal Puro T3 T4 Pz O2 Oz)', CnnLstm(AnalysisType.MUSIC_LIKE, FeatureType.CLINICAL_T3_T4_Pz_O2_Oz))
    MUSIC_LIKE_COMMON_SPATIAL_PATTERN_4 = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas Common Spatial Pattern 4 Valores)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.COMMON_SPATIAL_PATTERNS_4))
    MUSIC_LIKE_COMMON_SPATIAL_PATTERN_10 = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas Common Spatial Pattern 10 Valores)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.COMMON_SPATIAL_PATTERNS_10))
    MUSIC_LIKE_COMMON_SPATIAL_PATTERN_20 = ('Cenario para Gosto Musical (CNN + LSTM + caracteristicas Common Spatial Pattern 20 Valores)', CnnLstmFeatures(AnalysisType.MUSIC_LIKE, FeatureType.COMMON_SPATIAL_PATTERNS_20))
    MUSIC_LIKE_TRANFORMER_CLINICAL_FEATURE = ('Cenario para Gosto Musical (CNN + Transformer + caracteristicas clinicas)', CnnTranformerEncodeFeatures(AnalysisType.MUSIC_LIKE, FeatureType.CLINICAL))
    MUSIC_LIKE_TRANFORMER_COHERENCE_AND_CLINICAL_FEATURE = ('Cenario para Gosto Musical (CNN + Transformer + caracteristicas Coerência)', CnnTranformerEncodeFeatures(AnalysisType.MUSIC_LIKE, FeatureType.COHERENCE_AND_CLINICAL))
    MUSIC_LIKE_STATISTIC_TUNNING_FEATURE = ('Cenario para Gosto Musical (CNN + Tunning + caracteristicas coerencia e clinicas)', CnnTunningFeatures(AnalysisType.MUSIC_LIKE, FeatureType.COHERENCE_AND_CLINICAL))
    RIGHT_ARM_STATISTIC_FEATURE = ('Cenario para Braço direita e passo (CNN + LSTM + caracteristicas estatisticas)', CnnTunningFeatures(AnalysisType.RIGHT_ARM, FeatureType.STATISTIC))
    RIGHT_ARM_TRANFORMER_STATISTIC_FEATURE = ('Cenario para Braço direita e passo (CNN + Transformer + caracteristicas estatisticas)', CnnTranformerEncodeFeatures(AnalysisType.RIGHT_ARM, FeatureType.STATISTIC))    
    RIGHT_ARM_PCP_FEATURE = ('Cenario para Braço direito e passo (CNN + LSTM + caracteristicas de PCP)', CnnLstmFeatures(AnalysisType.RIGHT_ARM, FeatureType.PCP))
    RIGHT_ARM_FM_FEATURE = ('Cenario para Braço direito e passo (CNN + LSTM + caracteristicas de FM)', CnnLstmFeatures(AnalysisType.RIGHT_ARM, FeatureType.FM))
    RIGHT_ARM_COHERENCE_FEATURE = ('Cenario para Braço direito e passo (CNN + LSTM + caracteristicas de Coerência)', CnnLstmFeatures(AnalysisType.RIGHT_ARM, FeatureType.COHERENCE))
    DATA_MOTOR_IMAGINARY_STATISTIC_FEATURE = ('Cenario para Imaginação Motora (CNN + LSTM + caracteristicas estatisticas)', CnnTunningFeatures(AnalysisType.DATA_MOTOR_IMAGINARY, FeatureType.STATISTIC))
    DATA_MOTOR_IMAGINARY_TRANFORMER_STATISTIC_FEATURE = ('Cenario para Imaginação Motora (CNN + Transformer + caracteristicas estatisticas)', CnnTranformerEncodeFeatures(AnalysisType.DATA_MOTOR_IMAGINARY, FeatureType.STATISTIC))    
    DATA_MOTOR_IMAGINARY_PCP_FEATURE = ('Cenario para Imaginação Motora (CNN + LSTM + caracteristicas de PCP)', CnnLstmFeatures(AnalysisType.DATA_MOTOR_IMAGINARY, FeatureType.PCP))
    DATA_MOTOR_IMAGINARY_FM_FEATURE = ('Cenario para Imaginação Motora (CNN + LSTM + caracteristicas de FM)', CnnLstmFeatures(AnalysisType.DATA_MOTOR_IMAGINARY, FeatureType.FM))
    DATA_MOTOR_IMAGINARY_WAVELET_DECOMPOSITION_FEATURE = ('Cenario para Imaginação Motora (CNN + LSTM + caracteristicas de Decomposição Wavelet)', CnnLstmFeatures(AnalysisType.DATA_MOTOR_IMAGINARY, FeatureType.WAVELET_DECOMPOSITION))
    

    def __new__(cls, description, model_class):
        obj = object.__new__(cls)
        obj.description = description
        obj.model_class = model_class
        return obj